### ISSUE TITLE
nice project!

### ISSUE THREAD

**Issue by aquynh** [polazarus/capstone-sys.rs#1]
hi, is this a new Rust binding for Capstone? great, just wondering the difference between this and https://github.com/richo/capstone-rs?

cheers.

**Comment by polazarus** [comment]
Hi, yes and no...

It's just a low-level binding a quick and (not so) dirty translation of capstone headers files.
In the Rust world, *-sys packages are just for that traditionally.

My idea is that capstone-rs ultimately uses my low-level binding to connect to capstone. That will be for the better because for now capstone-rs is still missing lots of features (e.g. cs_detail and architecture-specific stuff).

Cheers
